### ISSUE TITLE
test_1_to_1_events failed in lksctp 1.0.18

### ISSUE THREAD

**Issue by code-share1** [sctp/lksctp-tools#25]
cd /usr/lib64/lksctp-tools/ptest
 ./test_1_to_1_events
test_1_to_1_events.c  1 PASS : COMM_UP notification on client socket - SUCCESS
test_1_to_1_events.c  2 PASS : COMM_UP notification on server socket - SUCCESS
test_1_to_1_events.c  3 BROK : Got a datamsg, expecting notification
DUMP_CORE sctputil.c: 187
Segmentation fault

**Comment by marceloleitner** [comment]
Which commit did you use and on which kernel?

**Comment by code-share1** [comment]
e5952a0cdfa8b1b56a5823574835f1f771f14ae0
kernel 4.18.7

**Comment by marceloleitner** [comment]
Alright. I'll look into it.

**Comment by marceloleitner** [comment]
Hah, yes. Wow.
```
main(int argc, char *argv[])
{
...
        struct sctp_event_subscribe event;
...
        event.sctp_data_io_event = 1;
        event.sctp_association_event = 1;
        event.sctp_shutdown_event = 1;
        len = sizeof(struct sctp_event_subscribe);
        test_setsockopt(svr_sk, SCTP_EVENTS, &event, len);
        test_setsockopt(clt_sk, SCTP_EVENTS, &event, len);
}
```

That is, event is a stack variable which was never properly initialized. AUTH_NO_AUTH event is only fired if we enable sctp_authentication_event, which we did not but was getting by with it being set by some garbage left in there. Please try:

```
--- a/src/func_tests/test_1_to_1_events.c
+++ b/src/func_tests/test_1_to_1_events.c
@@ -92,9 +92,11 @@ main(int argc, char *argv[])
        /* Create the client socket.  */
        clt_sk = test_socket(AF_INET, SOCK_STREAM, IPPROTO_SCTP);

+       memset(&event, 0, sizeof(event));
        event.sctp_data_io_event = 1;
        event.sctp_association_event = 1;
        event.sctp_shutdown_event = 1;
+       event.sctp_authentication_event = 1;
        len = sizeof(struct sctp_event_subscribe);
        test_setsockopt(svr_sk, SCTP_EVENTS, &event, len);
        test_setsockopt(clt_sk, SCTP_EVENTS, &event, len);

(
```whitespace damaged, copy&paste)

**Comment by marceloleitner** [comment]
In all other tests on which notifications are used, this is properly handled already.

**Comment by code-share1** [comment]
Thanks! the problem is solved
