### ISSUE TITLE
github releases have duplicated name

### ISSUE THREAD

**Issue by mbiebl** [sctp/lksctp-tools#26]
When trying to download a release tarball from https://github.com/sctp/lksctp-tools/releases, say https://github.com/sctp/lksctp-tools/archive/lksctp-tools-1.0.18.tar.gz, the file will be named
lksctp-tools-lksctp-tools-1.0.18.tar.gz when you try to download it.

The problem afaics is that you should pick 1.0.18 as release version and not lksctp-tools-1.0.18 as the project name is prefixed automatically

**Comment by marceloleitner** [comment]
Ack. We wanted to maintain the tag names that were used before but that didn't work well.
There you go:
https://github.com/sctp/lksctp-tools/releases/tag/v1.0.18

Will keep to this naming from now on.
Thanks

**Comment by mbiebl** [comment]
Thanks for the quick reply.
While I have your attention, I was wondering if github.com is the new canonical location for getting the release tarballs seeing that https://sourceforge.net/projects/lksctp/files/lksctp-tools/ does not have the 1.0.18 release.
If so, http://lksctp.sourceforge.net/ should probably be updated. 
When searching for lksctp-tools the sf website is the first hit.
