### ISSUE TITLE
soversion is not properly set for 1.0.18

### ISSUE THREAD

**Issue by mbiebl** [sctp/lksctp-tools#28]
Version: 1.0.18

After running ```make install```, the library is installed as
```/usr/lib/libsctp.so.1.0.17```
```/usr/lib/lksctp-tools/libwithsctp.so.1.0.17```

The soversion should not be tied to the package version. See
 https://autotools.io/libtool/version.html

**Comment by marceloleitner** [comment]
Yep. This one was fixed by 7de2bd7e769f10521e3d0c2cb42c6f6b9b505dd0 , also not part of a release yet.
7c0ef4d441b3833e721df58f56e2cb8c81b34df4 is also related to this.

Btw, there is one patch still on review for issue 25, and then I'll do a new release with these fixes.

**Comment by mbiebl** [comment]
I don't think this is properly fixed. The soversion should *not* be tied to the package version.
Quoting from the referenced documentation
```
The rules of thumb, when dealing with these values are:

- Always increase the revision value.
- Increase the current value whenever an interface has been added, removed or changed.
- Increase the age value only if the changes made to the ABI are backward compatible.

The main reason for which libtool uses this scheme for version information, is that it allows to have multiple version of a given library installed, with both link editor and dynamic linker choosing the latest available at build and run time. With modern distributions packaging standards, this situation should not be happening anyway.

Another common mistake is to match the value of -version-info with the package version or vice-versa. The two values are not designed to match: current increases with any interface change, compatible or not, and revision should be incremented with any package version.
```

**Comment by marceloleitner** [comment]
Fair point, but please keep in mind that's a general recommendation. In here what we are effectively packaging is the library itself. Considering we are (trying to) doing those rules for increasing the version number on both, do you see actual issues from versioning the package after the library in this case?
We could have lksctp-tools "4" with library "2:0:1", yes, but again, considering that the main deliverable is the library itself, that would just mask the information. Not sure how this would help out here.

**Comment by mbiebl** [comment]
If you are not using the library versioning as it it supposed to be, I don't see the point to version it at all.
You could just as well set it to 0:0:0. The library version should reflect API additions/removals/changes not the package version number.

**Comment by marceloleitner** [comment]
You didn't answer my question, but okay.

As I said, It's the other way around. The package is versioned after
the library, which is the main deliverable. I see no technical issues
that can arise from doing so. If you want libsctp.so.1, it will be
from lksctp-tools-1.y.z. If you want libsctp.so.2, fine, it will be
from lksctp-tools-2.y.z, and you may even have both in your system at
the same time.

This is done by other projects too. One quick example:

$ rpm -ql qt5-qtmultimedia-5.11.1-2.fc28.x86_64
                           ^^^^^^
...
/usr/lib64/libQt5Multimedia.so.5
/usr/lib64/libQt5Multimedia.so.5.11
/usr/lib64/libQt5Multimedia.so.5.11.1
/usr/lib64/libQt5MultimediaGstTools.so.5
/usr/lib64/libQt5MultimediaGstTools.so.5.11
/usr/lib64/libQt5MultimediaGstTools.so.5.11.1
...

Whose src is downloaded from:
Source0: https://download.qt.io/official_releases/qt/%{majmin}/%{version}/submodules/%{qt_module}-everywhere-src-%{version}.tar.xz
where %{version} expanding to the version highlighted above.

Still not sure why you think it is an issue here.

Although yes, we should have bumped the 'current' value when we added
a couple of features lately. That was an overlook and note was taken
already, specially after the couple of fixups we had after the last
release.

**Comment by mbiebl** [comment]
commit 7de2bd7e769f10521e3d0c2cb42c6f6b9b505dd0 says
```

Add CURRENT REVISION and AGE for libsctp and libwithsctp in
configure.ac to update these 2 library version information.

Compatible with before, they will start from 1:18:0. But each
will get updated according to their definitions in the future.
```
On the other hand, 7c0ef4d441b3833e721df58f56e2cb8c81b34df4 hard-codes the library-version via PACKAGE_VERSION

This doesn't make sense.

Either the version info libsctp and libwithsctp is handled independently from the package version (which 7de2bd7e769f10521e3d0c2cb42c6f6b9b505dd0 indicates will be the case). In which case 7c0ef4d441b3833e721df58f56e2cb8c81b34df4 is incorrect and should *not* use PACKAGE_VERSION but the actual version info of libwithsctp.

Or the library version of  libsctp/libwithsctp is strictly the package version.
In which case introducing
```
AC_SUBST(LIBSCTP_CURRENT, 1)
AC_SUBST(LIBSCTP_REVISION, 18)
AC_SUBST(LIBSCTP_AGE, 0)
AC_SUBST(LIBWITHSCTP_CURRENT, 1)
AC_SUBST(LIBWITHSCTP_REVISION, 18)
AC_SUBST(LIBWITHSCTP_AGE, 0)
```
I hope you see the inconsistency here.

**Comment by marceloleitner** [comment]
Yep, thanks. 7c0ef4d441b was wrong on hardcoding it to
PACKAGE_VERSION.

It's changelog is also not accurate, as we have no intention on
doing updating those versions async. The idea on that patch was
basically to make those settings not hardcoded in Makefile.am spread
through out in the src (as clearly I had forgotten to update them when
doing the 1.0.18 release). As they were the same but not linked to the
same number, Xin was conservative and keep them apart.

How about if we create one set of current:revision:age, to be used by
the package version and also both libs? That way we are sure we cannot
have libraries with confusing versions if compared to the package one,
and we solve this possible inconsistency of updating one and not the
other.

**Comment by marceloleitner** [comment]
@lxin , please chime in if you want.
