### ISSUE TITLE
sctp_recvmsg uses msg_flags as input argument

### ISSUE THREAD

**Issue by dfranusic** [sctp/lksctp-tools#31]
I was having strange issues with `sctp_recvmsg` repeating the same data and causing occasional infinite loops. Apparently, it was caused by  `msg_flags` not being initialized to zero. I was under the impression that `msg_flags` was output only argument, but when I looked at the source code I realized that it is being passed to `recvmg` as `flags` input argument. In my particular case I suspect that `MSG_PEEK `flag was somehow sent to `recvmsg`. Man pages should be updated to indicate this since it can cause undefined behavior and it's quite difficult to figure out what's going on.

**Comment by marceloleitner** [comment]
Agree. man page definitely should mention that the argument is overloaded.

**Comment by dfranusic** [comment]
Posted the patch to inux-sctp@vger.kernel.org

**Comment by marceloleitner** [comment]
Commit applied. Thanks!
