### ISSUE TITLE
SCTP ERROR: socket: Protocol not supported on aarch64 for Linux.

### ISSUE THREAD

**Issue by yunfan188** [sctp/lksctp-tools#36]
My working computer info as follows: 
$ uname -a
Linux centos-arm 4.18.0-80.7.2.el7.aarch64 #1 SMP Thu Sep 12 16:13:20 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
$ cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (AltArch)
I have installed sctp lib,its version: lksctp-tools-1.0.17.tar.gz.
my execute file dependent libraries info: $ ldd sctp_svr
        linux-vdso.so.1 =>  (0x0000ffff876a0000)
        libsctp.so.1 => /home/mals/cu/local/lib/libsctp.so.1 (0x0000ffff87660000)
        libc.so.6 => /lib64/libc.so.6 (0x0000ffff874d0000)
        /lib/ld-linux-aarch64.so.1 (0x0000ffff876b0000)
but when I run my bin file: ./sctp_svr 192.168.0.128 9998
socket: Protocol not supported

The relative code as follows:
listen_sock=socket(AF_INET, SOCK_STREAM, IPPROTO_SCTP);  //create a sctp socket
        if(listen_sock == -1){
		perror("socket");
		return -1;
	}

So, I want to know whether the sctp third lib does not support arm64 arch for Linux or not?

**Comment by marceloleitner** [comment]
On Thu, Jul 16, 2020 at 07:50:37PM -0700, yunfan188 wrote:
> So, I want to know whether the sctp third lib does not support arm64 arch for Linux or not?

It is supported, but you need two things:
- install kernel-modules-extra package (sctp.ko is there)
- un-blacklist the sctp module in /etc/modprobe.d/sctp-blacklist.conf

Btw, not related but you may want to update that kernel, if possible.

**Comment by marceloleitner** [comment]
On Thu, Jul 16, 2020 at 07:50:37PM -0700, yunfan188 wrote:
> My working computer info as follows: 
> $ uname -a
> Linux centos-arm 4.18.0-80.7.2.el7.aarch64 #1 SMP Thu Sep 12 16:13:20 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
> $ cat /etc/redhat-release 
> CentOS Linux release 7.6.1810 (AltArch)

Actually, I don't know where this kernel is from. What I replied,
applies to CentOS 8. I read "4.18.0" and assumed this was a el8
system, but not. Then it may be possible that sctp support is not
enabled.

Where did you get it?
