### ISSUE TITLE
SCTP problem on kernel 4.18.0-193 or later

### ISSUE THREAD

**Issue by poekmorgan** [sctp/lksctp-tools#38]
We have two samples of java code, one acts a SCTP server, and the other acts as SCTP client, it is developed in order to test the behavior on RHEL6 and on RHEL8. and the code is not really using netty, so it is purely on java (OpenJDK) and LKSCTP.

On RHEL6.RHEL7 and RHEL8.0 (4.18.0-80.el8.x86_64), the utilities works normal, however, the similar setup on RHEL8.2 is not working. 

Sample results as below.

OpenJDK14 on RHEL6
===================
### SERVER ###
$ uname -a
Linux rhel6-test001 2.6.32-754.17.1.el6.x86_64 #1 SMP Thu Jun 20 11:47:12 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux

$ rpm -qa|grep lksctp
lksctp-tools-devel-1.0.10-7.el6.x86_64
lksctp-tools-doc-1.0.10-7.el6.x86_64
lksctp-tools-1.0.10-7.el6.x86_64

$ java -version
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-46)
OpenJDK 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)

$ java TestSctpSvr 10.165.241.119 3868
SCTP_INIT_MAXSTREAMS,in = 65535, out = 10
SCTP_INIT_MAXSTREAMS,in = 10, out = 20
Client connection received from [/10.165.241.90:1111], association = sun.nio.ch.sctp.AssociationImpl@2d98a335[associationID:865, maxIn:10, maxOut:20]
after connect, SCTP_INIT_MAXSTREAMS from assoc,in = 10, out = 20
Received a messagesun.nio.ch.sctp.MessageInfoImpl@7ef20235[Address: /10.165.241.90:1111, Association: sun.nio.ch.sctp.AssociationImpl@2d98a335[associationID:865, maxIn:10, maxOut:20], Assoc ID: 865, Bytes: 1000, Stream Number: 0, Complete: true, isUnordered: false]
### CLIENT ####

$ uname -a
Linux rhel6-test002 2.6.32-754.17.1.el6.x86_64 #1 SMP Thu Jun 20 11:47:12 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux

$ rpm -qa|grep lksctp
lksctp-tools-devel-1.0.10-7.el6.x86_64
lksctp-tools-1.0.10-7.el6.x86_64
lksctp-tools-doc-1.0.10-7.el6.x86_64

$ java -version
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-46)
OpenJDK 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)

$ java TestSctpCli 10.165.241.90 1111  10.165.241.119 3868
SO_RCVBUF = 65536
SO_SNDBUF = 65536
SCTP_DISABLE_FRAGMENTS = false
SCTP_INIT_MAXSTREAMS,in = 65535, out = 10
SCTP_INIT_MAXSTREAMS,in = 100, out = 200
after connect, SCTP_INIT_MAXSTREAMS from assoc,in = 20, out = 10
sending packet 0 of size 1000, retval = 1000
sending packet 1 of size 1000, retval = 1000
sending packet 2 of size 1000, retval = 1000
sending packet 3 of size 1000, retval = 1000
sending packet 4 of size 1000, retval = 1000
sending packet 5 of size 1000, retval = 1000
sending packet 6 of size 1000, retval = 1000
sending packet 7 of size 1000, retval = 1000
sending packet 8 of size 1000, retval = 1000

sending packet 9 of size 1000, retval = 1000
sending packet 10 of size 1000, retval = 1000
sending packet 11 of size 1000, retval = 1000
sending packet 12 of size 1000, retval = 1000
sending packet 13 of size 1000, retval = 1000
sending packet 14 of size 1000, retval = 1000

OpenJDK14 on RHEL8.2 (NOT WORKING)
===================================
### SERVER ###

$ uname -a
Linux rhel8-test001 4.18.0-193.13.2.el8_2.x86_64 #1 SMP Mon Jul 13 23:17:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ rpm -qa |grep lksctp-tools
lksctp-tools-devel-1.0.18-3.el8.x86_64
lksctp-tools-1.0.18-3.el8.x86_64
lksctp-tools-doc-1.0.18-3.el8.x86_64

$ java -version
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-46)
OpenJDK 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)
$ java TestSctpSvr 10.164.208.186 3868
SCTP_INIT_MAXSTREAMS,in = 65535, out = 10
SCTP_INIT_MAXSTREAMS,in = 10, out = 20
Client connection received from [/10.164.208.185:1111], association = null
Exception in thread "main" java.lang.NullPointerException
	at TestSctpSvr.main(TestSctpSvr.java:41)

### CLIENT ###

$ uname -a
Linux rhel8-test002 4.18.0-193.14.3.el8_2.x86_64 #1 SMP Mon Jul 20 15:02:29 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ rpm -qa |grep lksctp-tools
lksctp-tools-devel-1.0.18-3.el8.x86_64
lksctp-tools-doc-1.0.18-3.el8.x86_64
lksctp-tools-1.0.18-3.el8.x86_64

$ java -version
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-46)
OpenJDK 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)
[dscadm@da1t-gen-dsc-app001:RHEL8_APP01:~ ]$ 

$ java TestSctpCli 10.164.208.185 1111 10.164.208.186 3868
SO_RCVBUF = 65536
SO_SNDBUF = 65536
SCTP_DISABLE_FRAGMENTS = false
SCTP_INIT_MAXSTREAMS,in = 65535, out = 10
SCTP_INIT_MAXSTREAMS,in = 100, out = 200
Exception in thread "main" java.lang.NullPointerException
	at TestSctpCli.main(TestSctpCli.java:42)

**Comment by pgrabowski** [comment]
FYI there will be a fix in Red Hat Linux kernel for this issue.

**Comment by marceloleitner** [comment]
@pgrabowski is right. The issue will be fixed by including this commit https://lkml.org/lkml/2020/6/9/972, tracked via rhbz 1878308.
That said, there's nothing to be fixed in lksctp-tools, so I'll close this issue. Thanks.
