### ISSUE TITLE
Does not install header file

### ISSUE THREAD

**Issue by htgoebel** [sctp/lksctp-tools#41]
When installing the package, the header-file `sctp.h` ist not installed. Instead `sctp.h.in` is installed.

#### How to reprodce:
- fresh clone of repo
- ./bootstrap
- ./configure
- make
- make DESTDIR=$PWD install
- ls usr/include/netinet/
sctp.h.in

## Expected
sctp.h is installed:

- ls usr/include/netinet/
sctp.h

**Comment by htgoebel** [comment]
Possible fix: <http://svnweb.mageia.org/packages/cauldron/lksctp-tools/current/SOURCES/lksctp-tools-1.0.18-fix-header-file-name.patch?view=co>

**Comment by marceloleitner** [comment]
Precisely, which is available here on commit 378560050a8f93786c590cc99a55461666205b61, available on master branch.
Thanks.

**Comment by htgoebel** [comment]
MAy I ask you are a new release?! This commit is more than two years old, and still not in a release. It took me more than an hour to find and solve this. A release would avoid others to step into the same trap. Thanks.

**Comment by marceloleitner** [comment]
I'm sorry to hear that.
That's a really good point. I'll work on a release later this week.
