### ISSUE TITLE
Provide consistent information on where the project home / contact is (SourceForge or GitHub?)

### ISSUE THREAD

**Issue by stepnem** [sctp/lksctp-tools#44]
Compared to GitHub, the SourceForge project seems inactive:

https://sourceforge.net/p/lksctp/activity/ (last activity 2 years ago)

https://sourceforge.net/p/lksctp/mailman/lksctp-developers/?page=0 (last message 2013)

but many places still list the SourceForge URLs and e-mail address, e.g.:

README:

```
http://www.sourceforge.net/projects/lksctp

	This is the lksctp project webpage. 
```

C file headers (e.g. sctp_test.c):

```
 * Please send any bug reports or fixes you make to the
 * email address(es):
 *    lksctp developers <lksctp-developers@lists.sourceforge.net>
 *
 * Or submit a bug report through the following website:
 *    http://www.sf.net/projects/lksctp
 ```

RPM spec file:

```
URL: http://lksctp.sourceforge.net
```

**Comment by marceloleitner** [comment]
Agreed. Also the correct mailing list these days is another: `linux-sctp@vger.kernel.org`

**Comment by marceloleitner** [comment]
https://lksctp.sourceforge.net/ page was updated to redirect to the new page that now sits on github wiki here:  https://github.com/sctp/lksctp-tools/wiki

**Comment by marceloleitner** [comment]
(which still needs some updating)
