### ISSUE TITLE
sctp_test do not support stream num >= 10.

### ISSUE THREAD

**Issue by jiachenjun** [sctp/lksctp-tools#5]
when setting the stream number >=10 the data send failed.
output attached below.

I have already submit the correction patch.
47fd2fbd1d63bb38a23b578cfe18bcf9e28b5db2

sctp_test -H localhost -P 1111 -h localhost -p 1234 -M 10 -s
remote:addr=127.0.0.1, port=1234, family=2
local:addr=127.0.0.1, port=1111, family=2
seed = 1473471140

Starting tests...
        socket(SOCK_SEQPACKET, IPPROTO_SCTP)  ->  sk=3
        bind(sk=3, [a:127.0.0.1,p:1111])  --  attempt 1/10
Client: Sending packets.(1/10)
        sendmsg(sk=3, assoc=0)    1 bytes.
          SNDRCV(stream=1 flags=0x1 ppid=1339736500
        sendmsg(sk=3, assoc=0)    1 bytes.
          SNDRCV(stream=2 flags=0x1 ppid=729094762
        sendmsg(sk=3, assoc=0)    1 bytes.
          SNDRCV(stream=3 flags=0x1 ppid=2136564246
        sendmsg(sk=3, assoc=0)    1 bytes.
          SNDRCV(stream=4 flags=0x1 ppid=567955794
        sendmsg(sk=3, assoc=0)    1 bytes.
          SNDRCV(stream=5 flags=0x1 ppid=1836674414
        sendmsg(sk=3, assoc=0)    1 bytes.
          SNDRCV(stream=6 flags=0x1 ppid=1521744644
        sendmsg(sk=3, assoc=0)    1 bytes.
          SNDRCV(stream=7 flags=0x1 ppid=454423727
        sendmsg(sk=3, assoc=0)    1 bytes.
          SNDRCV(stream=8 flags=0x1 ppid=1657565844
        sendmsg(sk=3, assoc=0)    1 bytes.
          SNDRCV(stream=9 flags=0x1 ppid=1754994355
        sendmsg(sk=3, assoc=0)    1 bytes.
          SNDRCV(stream=10 flags=0x1 ppid=1453090822

```
            *** sendmsg: Invalid argument ***
```

**Comment by marceloleitner** [comment]
Integrated on commit 90460dfb97a596512a396d6c2dc168751cfad9ab. Thanks
