### ISSUE TITLE
SCTP_SENDALL

### ISSUE THREAD

**Issue by cmcdowellNREC** [sctp/lksctp-tools#52]
Hello,

Is the SCTP_SENDALL flag implemented in the latest version, 1.0.19?

Thanks,
Caleb

**Comment by century6** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=4910280503f3af2857d5aa77e35b22d93a8960a8

**Comment by lxin** [comment]
That's right, you only need to set SCTP_SENDALL to "flags" when calling sctp_sendmsg().
Anyway, we should update our man doc in man/sctp_sendmsg.3.

Thanks.
