### ISSUE TITLE
Support for SCTP AUTH

### ISSUE THREAD

**Issue by lvc1** [sctp/lksctp-tools#57]
Hi,

I am trying to configure SCTP AUTH extension. After enabling 'sysctl net.sctp.auth_enable=1' AUTH chunk list in INIT msg is empty. Since I am working in Java I am not able to call setsockopt(SCTP_AUTH_CHUNK). Is there any other way to configure it?

Thanks

**Comment by lxin** [comment]
I don't think so. I'm afraid you have to extend Socket in some way in Java, or check if you can invoke syscall(__NR_setsockopt=294) via some Java Native class.

**Comment by lvc1** [comment]
Hi, I managed to set it calling native method in Java.

Thanks!
