### ISSUE TITLE
SCTP_PEER_ADDR_CHANGE

### ISSUE THREAD

**Issue by tulu1688** [sctp/lksctp-tools#6]
I tested sctp connection between two host in one-to-many mode.

In client side (IP "10.10.10.10") I use connect (instead of connectx) function to server IP "10.20.30.40". In server side I use bind (instead of bindx) to IP "10.20.30.40". My code work well about 20 minutes the server got two SCTP_PEER_ADDR_CHANGE event:
^^^ intf_change: 10.10.10.10 state=1, error=0
^^^ intf_change: 10.10.10.10 state=0, error=1
After these event, the server could not receive packets anymore. What will I do to keep the connection permanent.

Bellow is the code:
- Client side:
  server_addr.sin_family = AF_INET;
  server_addr.sin_port = htons(10001);
  inet_pton(AF_INET, "10.20.30.40", &server_addr.sin_addr);
  sock_fd = socket(AF_INET, SOCK_SEQPACKET, IPPROTO_SCTP);
  connect(sock_fd, (struct sockaddr *) &server_addr, sizeof(server_addr));
  // Some set event, send message and receive code 
- Server side:
  static void
  handle_event(void *buf)
  {
  struct sctp_assoc_change    *sac;
  struct sctp_send_failed     *ssf;
  struct sctp_paddr_change    *spc;
  struct sctp_remote_error    *sre;
  union sctp_notification     *snp;
  char                addrbuf[INET6_ADDRSTRLEN];
  const char          *ap;
  struct sockaddr_in      *sin;
  struct sockaddr_in6     *sin6;
  
  snp = buf;
  
  switch (snp->sn_header.sn_type) {
  case SCTP_ASSOC_CHANGE:
      sac = &snp->sn_assoc_change;
      printf("^^^ assoc_change: state=%hu, error=%hu, instr=%hu "
          "outstr=%hu\n", sac->sac_state, sac->sac_error,
          sac->sac_inbound_streams, sac->sac_outbound_streams);
      break;
  case SCTP_SEND_FAILED:
      ssf = &snp->sn_send_failed;
      printf("^^^ sendfailed: len=%hu err=%d\n", ssf->ssf_length,
          ssf->ssf_error);
      break;
  case SCTP_PEER_ADDR_CHANGE:
      spc = &snp->sn_paddr_change;
      if (spc->spc_aaddr.ss_family == AF_INET) {
          sin = (struct sockaddr_in *)&spc->spc_aaddr;
          ap = inet_ntop(AF_INET, &sin->sin_addr, addrbuf,
              INET6_ADDRSTRLEN);
      } else {
          sin6 = (struct sockaddr_in6 *)&spc->spc_aaddr;
          ap = inet_ntop(AF_INET6, &sin6->sin6_addr, addrbuf,
              INET6_ADDRSTRLEN);
      }
      printf("^^^ intf_change: %s state=%d, error=%d\n", ap,
          spc->spc_state, spc->spc_error);
      break;
  case SCTP_REMOTE_ERROR:
      sre = &snp->sn_remote_error;
      printf("^^^ remote_error: err=%hu len=%hu\n",
          ntohs(sre->sre_error), ntohs(sre->sre_length));
      break;
  case SCTP_SHUTDOWN_EVENT:
      printf("^^^ shutdown event\n");
      break;
  default:
      printf("unknown type: %hu\n", snp->sn_header.sn_type);
      break;
  }
  }

main() {
...
       if ((lfd = socket(AF_INET, SOCK_STREAM, IPPROTO_SCTP)) == -1) {
        perror("socket");
        exit(1);
    }

```
sin->sin_family = AF_INET;
sin->sin_port = htons(1117);
sin->sin_addr.s_addr = inet_addr("10.20.30.40");
if (bind(lfd, (struct sockaddr *)sin, sizeof (*sin)) == -1) {
    perror("bind");
    exit(1);
}

if (listen(lfd, 1) == -1) {
    perror("listen");
    exit(1);
}
```

...
}

**Comment by marceloleitner** [comment]
By any chance, did you find the reason already?
"^^^ intf_change: 10.10.10.10 state=0, error=1" is weird because state=0 means SCTP_COMM_UP and there is no place that emits that state with error != 0.
